server:
  port: 7001
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/testdb
        username: root
        password: Root@12345

    jpa:
        generate-ddl: true
        show-sql: true
        
        hibernate:
            ddl-auto: create
            dialect: org.hibernate.dialect.MySQL8Dialect
